import type { Craft } from "./components/CraftNode";

// 示例数据 - 包含关系
export const mockCrafts: Craft[] = [
  {
    id: "1",
    name: "Glassmorphism Card",
    description: "A beautiful frosted glass effect card component with blur and transparency",
    category: "component",
    technologies: ["React", "CSS", "Backdrop-filter"],
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600",
    createdAt: "2024-12-20",
    featured: true,
    weight: 2,
  },
  {
    id: "2",
    name: "Magnetic Button",
    description: "Interactive button that follows cursor with magnetic effect",
    category: "effect",
    technologies: ["React", "Framer Motion", "TypeScript"],
    coverImage: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=600",
    createdAt: "2024-12-15",
    weight: 1.5,
    relations: [{ targetId: "6", type: "uses" }],
  },
  {
    id: "3",
    name: "Infinite Scroll Gallery",
    description: "Smooth infinite scrolling image gallery with lazy loading",
    category: "component",
    technologies: ["React", "Intersection Observer", "CSS Grid"],
    coverImage: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600",
    createdAt: "2024-12-10",
    featured: true,
    weight: 1.5,
    relations: [{ targetId: "1", type: "extends" }],
  },
  {
    id: "4",
    name: "3D Flip Card",
    description: "Card component with smooth 3D flip animation on hover",
    category: "effect",
    technologies: ["CSS 3D", "Transform", "Perspective"],
    coverImage: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=600",
    createdAt: "2024-12-05",
    weight: 1,
    relations: [
      { targetId: "1", type: "variant" },
      { targetId: "7", type: "inspiredBy" },
    ],
  },
  {
    id: "5",
    name: "Custom Range Slider",
    description: "Fully customizable range slider with gradient track",
    category: "control",
    technologies: ["React", "CSS Variables", "TypeScript"],
    coverImage: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=600",
    createdAt: "2024-11-28",
    weight: 1,
  },
  {
    id: "6",
    name: "Particle System",
    description: "Interactive particle animation system with mouse interaction",
    category: "experiment",
    technologies: ["Canvas", "JavaScript", "RequestAnimationFrame"],
    coverImage: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=600",
    createdAt: "2024-11-20",
    featured: true,
    weight: 2,
  },
  {
    id: "7",
    name: "Morphing Shapes",
    description: "SVG shapes that smoothly morph between different forms",
    category: "experiment",
    technologies: ["SVG", "GSAP", "React"],
    coverImage: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600",
    createdAt: "2024-11-15",
    weight: 1.2,
    relations: [{ targetId: "6", type: "relatedTo" }],
  },
  {
    id: "8",
    name: "Drag & Drop List",
    description: "Smooth drag and drop reorderable list component",
    category: "control",
    technologies: ["React", "Framer Motion", "TypeScript"],
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    createdAt: "2024-11-10",
    weight: 1,
    relations: [{ targetId: "2", type: "uses" }],
  },
  {
    id: "9",
    name: "Animated Counter",
    description: "Number counter with smooth spring animations",
    category: "component",
    technologies: ["React", "Framer Motion"],
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600",
    createdAt: "2024-11-05",
    weight: 1,
  },
  {
    id: "10",
    name: "Spotlight Effect",
    description: "Mouse-following spotlight reveal effect",
    category: "effect",
    technologies: ["CSS", "JavaScript", "Clip-path"],
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600",
    createdAt: "2024-10-28",
    weight: 1,
    relations: [{ targetId: "2", type: "relatedTo" }],
  },
  {
    id: "11",
    name: "Toast Notifications",
    description: "Stackable toast notification system",
    category: "component",
    technologies: ["React", "TypeScript", "CSS"],
    coverImage: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600",
    createdAt: "2024-10-20",
    weight: 1,
  },
  {
    id: "12",
    name: "Skeleton Loader",
    description: "Animated skeleton loading placeholders",
    category: "component",
    technologies: ["React", "CSS Animation"],
    coverImage: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=600",
    createdAt: "2024-10-15",
    weight: 1,
    relations: [{ targetId: "1", type: "extends" }],
  },
  {
    id: "13",
    name: "Color Picker",
    description: "Advanced color picker with gradient and palette support",
    category: "control",
    technologies: ["React", "TypeScript", "Color Theory"],
    coverImage: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600",
    createdAt: "2024-10-10",
    weight: 1.2,
    relations: [{ targetId: "5", type: "relatedTo" }],
  },
  {
    id: "14",
    name: "Parallax Scroll",
    description: "Smooth parallax scrolling effect with multiple layers",
    category: "effect",
    technologies: ["JavaScript", "CSS Transform", "Scroll Events"],
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",
    createdAt: "2024-10-05",
    featured: true,
    weight: 1.8,
  },
  {
    id: "15",
    name: "Animated Menu",
    description: "Hamburger menu with smooth morphing animation",
    category: "component",
    technologies: ["React", "GSAP", "SVG"],
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600",
    createdAt: "2024-09-28",
    weight: 1,
    relations: [{ targetId: "7", type: "uses" }],
  },
  {
    id: "16",
    name: "Image Comparison Slider",
    description: "Before/after image comparison with draggable slider",
    category: "component",
    technologies: ["React", "TypeScript", "Clip-path"],
    coverImage: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=600",
    createdAt: "2024-09-20",
    weight: 1.3,
  },
  {
    id: "17",
    name: "Typing Animation",
    description: "Realistic typewriter effect with cursor blink",
    category: "effect",
    technologies: ["JavaScript", "CSS", "Animation"],
    coverImage: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=600",
    createdAt: "2024-09-15",
    weight: 1,
  },
  {
    id: "18",
    name: "Accordion Panel",
    description: "Smooth expanding accordion with nested support",
    category: "component",
    technologies: ["React", "Framer Motion", "TypeScript"],
    coverImage: "https://images.unsplash.com/photo-1557821552-17105176677c?w=600",
    createdAt: "2024-09-10",
    weight: 1,
    relations: [{ targetId: "2", type: "uses" }],
  },
  {
    id: "19",
    name: "Loading Spinner",
    description: "Collection of creative loading animations",
    category: "component",
    technologies: ["CSS Animation", "SVG"],
    coverImage: "https://images.unsplash.com/photo-1614850715649-1d0106293bd1?w=600",
    createdAt: "2024-09-05",
    weight: 1,
    relations: [{ targetId: "12", type: "relatedTo" }],
  },
  {
    id: "20",
    name: "Cursor Trail Effect",
    description: "Custom cursor with particle trail effect",
    category: "experiment",
    technologies: ["Canvas", "JavaScript", "RequestAnimationFrame"],
    coverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600",
    createdAt: "2024-08-30",
    featured: true,
    weight: 1.5,
    relations: [
      { targetId: "6", type: "extends" },
      { targetId: "10", type: "relatedTo" },
    ],
  },
];