export const assistants = [
  {
    id: 'analytics',
    name: 'Data Neko',
    role: 'Analysis',
    description: '网站流量和用户行为分析。',
    accent: '#96BAFF',
    item: 'laptop',
    catColors: {
      body: '#3D3D3D',
      bodyDark: '#2A2A2A',
      belly: '#3D3D3D',
      earInner: '#E8909A',
      eyes: '#000',
      nose: '#542615',
      blush: '#F28686',
      stroke: '#1A1A1A',
      apron: '#7EB8DA',
      apronLight: '#D6EAF5',
      apronLine: '#7EB8DA',
      desk: '#C8D8E8',
      deskDark: '#8BA4BD',
      deskLeg: '#A6BCCF',
      paw: '#fff',
       tail: '#3D3D3D',
       faceDark:'',
        month:'',
        head:'',
        bodyDarkBottom:'',
        leg:'',
        headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '今日UV上涨12%~ 📈',
      '跳出率有点高呢...',
      '让我分析一下数据!',
      '转化率创新高了! ✨',
      '用户画像已更新~',
    ]
  },
  {
    id: 'email',
    name: 'Postman',
    role: 'Newsletter',
    description: '将重要的数据结果送达您的邮箱。',
    accent: '#F2A5B9',
    item: 'mail',
    catColors: {
      body: '#F7AC5E',
      bodyDark: '#D3753E',
      belly: '',
      earInner: '#F28686',
      eyes: '#542615',
      nose: '#542615',
      blush: '#F28686',
      stroke: '#542615',
      apron: '#BDBDBD',
      apronLight: '#FEFFFE',
      apronLine: '#BDBDBD',
      desk: '#D7CCC8',
      deskDark: '#A1887F',
      deskLeg: '#BCAAA4',
      paw: '',
      tail: '#F7AC5E',
      faceDark:'',
       month:'',
       head:'',
       bodyDarkBottom:'',
        leg:'',
        headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '有3封新邮件! 📬',
      '周报已送达~',
      '订阅者又增加了!',
      '邮件送达率99%! 💌',
      '通知已全部发出~',
    ]
  },
  {
    id: 'writer',
    name: 'Sensei',
    role: 'Article Master',
    description: '文章润色、大纲生成与创意写作。',
    accent: '#FF6B6B',
    item: 'notebook',
    catColors: {
      body: '#F5F5F5',
      bodyDark: '#D5D5D5',
      belly: '#FFFFFF',
      earInner: '#FFB5C5',
      eyes: '#542615',
      nose: '#542615',
      blush: '#FFB5C5',
      stroke: '#333333',
      apron: '#E8A0BF',
      apronLight: '#FCE4EC',
      apronLine: '#E8A0BF',
      desk: '#E8C8D8',
      deskDark: '#C4919E',
      deskLeg: '#D4A8B5',
      paw: '#FFFFFF',
      tail: '#F5F5F5',
      faceDark:'',
       month:'',
       head:'',
       bodyDarkBottom:'',
       leg:'',
       headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '灵感来了! ✍️',
      '这段话可以更好~',
      '大纲已经拟好了!',
      '文章润色完成~ 📝',
      '要来点创意写作吗?',
    ]
  },
  {
    id: 'crafts',
    name: 'Artisan',
    role: 'Crafts Gen',
    description: '生成精美的创意组件代码。',
    accent: '#A0D8B3',
    item: 'palette',
    catColors: {
      body: '#B0A08A',
      bodyDark: '#5C4A3A',
      belly: '#FFFFFF',
      earInner: '#F4B8B8',
      eyes: '#B2D989',
      nose: '#E8998D',
      blush: '#F4B8B8',
      stroke: '#3E2E1E',
      apron: '#A5D6A7',
      apronLight: '#E8F5E9',
      apronLine: '#A5D6A7',
      desk: '#C8DEC4',
      deskDark: '#8DB889',
      deskLeg: '#A6CCA2',
      paw: '#FFFFFF',
      tail: '#B0A08A',
      faceDark:'',
      month:'',
      head:'',
      bodyDarkBottom:'',
      leg:'',
      headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '新组件出炉了! 🎨',
      '配色方案已生成~',
      '这个动画很流畅!',
      '代码已优化完毕~ ✨',
      '要做点什么创意?',
    ]
  },
  {
    id: 'image',
    name: 'Pixel',
    role: 'Image Gen',
    description: '根据描述生成精美的图片。',
    accent: '#90CAF9',
    item: 'camera',
    catColors: {
      body: '#FAF3EB',
      bodyDark: '#FAF3EB',
      belly: '#FAF3EB',
      earInner: '#4E342E',
      eyes: '#4FC3F7',
      nose: '#333',
      blush: '#FFCCBC',
      stroke: '#4E342E',
      apron: '#B39DDB',
      apronLight: '#EDE7F6',
      apronLine: '#B39DDB',
      desk: '#D1C4E9',
      deskDark: '#9575CD',
      deskLeg: '#B39DDB',
      paw: '#4E342E',
      tail: '#4E342E',
      faceDark:'#4E342E',
      month:'#333',
      head:'',
      bodyDarkBottom:'',
      leg:'',
      headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '画面构图中... 🖼️',
      '色彩搭配完成~',
      '高清大图生成中!',
      '这张图太美了! ✨',
      '想生成什么画面?',
    ]
  },
  {
    id: 'manager',
    name: 'Tama',
    role: 'Manager',
    description: '统筹管理所有小猫助手的工作。',
    accent: '#FFB74D',
    item: 'clipboard',
    catColors: {
      body: '#FAFAFA',
      bodyDark: '',
      belly: '#FFFFFF',
      earInner: '#FFB5C5',
      eyes: '#542615',
      nose: '#E8998D',
      blush: '#FFB5C5',
      stroke: '#5D4037',
      apron: '#FFB74D',
      apronLight: '#FFF3E0',
      apronLine: '#FFB74D',
      desk: '#FFE0B2',
      deskDark: '#FFB74D',
      deskLeg: '#FFCC80',
      paw: ['#5C4A3A','#FAFAFA','#F7AC5E','#FAFAFA'],
      tail: '#5C4A3A',
      faceDark: '',
      month: '',
      head:'#FAFAFA',
      bodyDarkBottom:'#F7AC5E',
      leg: ['#F7AC5E','#FAFAFA','#5C4A3A','#F7AC5E'],
      headTopLeft:'#F7AC5E',
      headTopRight:'#5C4A3A',
    },
    messages: [
      '大家都在努力工作呢~',
      '今天的任务已分配好!',
      '所有猫猫状态良好~',
      '工作进度已更新! 📋',
      '让我来协调一下~',
    ]
  },
   {
    id: 'text',
    name: 'Pixel',
    role: 'Image Gen',
    description: '根据描述生成精美的图片。',
    accent: '#90CAF9',
    item: 'camera',
    catColors: {
      body: '#FAF3EB',
      bodyDark: '#FAF3EB',
      belly: '#FAF3EB',
      earInner: '#F7AC5E',
      eyes: '#A1E0FF',
      nose: '#5D4037',
      blush: '#FFCCBC',
      stroke: '#5D4037',
      apron: '#B39DDB',
      apronLight: '#EDE7F6',
      apronLine: '#B39DDB',
      desk: '#B3E5FC',
      deskDark: '#4FC3F7',
      deskLeg: '#81D4FA',
      paw: '#F7AC5E',
      tail: '#F7AC5E',
      faceDark:'#F7AC5E',
      month:'#333',
      head:'',
      bodyDarkBottom:'',
      leg:'',
      headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '画面构图中... 🖼️',
      '色彩搭配完成~',
      '高清大图生成中!',
      '这张图太美了! ✨',
      '想生成什么画面?',
    ]
  },
  {
    id: 'sing',
    name: 'Pixel',
    role: 'Image Gen',
    description: '根据描述生成精美的图片。',
    accent: '#90CAF9',
    item: 'camera',
    catColors: {
      body: '#FFF',
      bodyDark: '#FFF',
      belly: '#FFF',
      earInner: '#FFF',
      eyes: '#5D4037',
      nose: '#5D4037',
      blush: '#FFCCBC',
      stroke: '#5D4037',
      apron: '#B39DDB',
      apronLight: '#EDE7F6',
      apronLine: '#B39DDB',
      desk: '#FFF9C4',
      deskDark: '#FDD835',
      deskLeg: '#FFF176',
      paw: '#FFF',
      tail: '#FFF',
      faceDark:'',
      month:'#333',
      head:'',
      bodyDarkBottom:'',
      leg:'',
      headTopLeft:'',
      headTopRight:'',
    },
    messages: [
      '画面构图中... 🖼️',
      '色彩搭配完成~',
      '高清大图生成中!',
      '这张图太美了! ✨',
      '想生成什么画面?',
    ]
  },
  {
    id: 'milk',
    name: 'Tama',
    role: 'Manager',
    description: '统筹管理所有小猫助手的工作。',
    accent: '#FFB74D',
    item: 'clipboard',
    catColors: {
      body: '#FFF',
      bodyDark: '',
      belly: '#FFFFFF',
      earInner: '#FFB5C5',
      eyes: '#000',
      nose: '#E8998D',
      blush: '#FFB5C5',
      stroke: '#5D4037',
      apron: '#FFB74D',
      apronLight: '#FFF3E0',
      apronLine: '#FFB74D',
      desk: '#F8BBD0',
      deskDark: '#EC407A',
      deskLeg: '#F48FB1',
      paw: ['#333','#FAFAFA','#333','#333'],
      tail: '#333',
      faceDark: '',
      month: '',
      head:'#FFF',
      bodyDarkBottom:'#333',
      leg: ['#FAFAFA','#333','#333','#FAFAFA'],
      headTopLeft:'#333',
      headTopRight:'#333',
    },
    messages: [
      '大家都在努力工作呢~',
      '今天的任务已分配好!',
      '所有猫猫状态良好~',
      '工作进度已更新! 📋',
      '让我来协调一下~',
    ]
  },
];